### ISSUE TITLE
不好意思，我的train訓練不起來，想請問有沒有遇到這類問題

### ISSUE THREAD

**Issue by firecoolman** [RunningChen/UprightRL#1]
不好意思，我在train的時候遇到以下問題  我的python版本是3.9.7在window10環境底下執行，剩下的都跟版主的環境設定一樣，只是每次到最後AttributeError: 'SummaryWriter' object has no attribute 'info'  這邊都會有問題，想請問版主有遇到過類似的問題嗎，或是請問能給我python與其他版本的資訊嗎，我目前按照版主的方法也都創好dataset 的資料夾了，想請問版主也遇到過類似問題或請教有什麼建議嗎，如果能回答的話 就太感激了，十分感謝
PS _AXES2TUPLE,_TUPLE2AXES,_NEXT_AXIS在trans中這3個變數not defined 不知道是不是這邊問題，想請問一下版主
PARAMETER ...
Namespace(lr=0.001, gamma=0.4, entropy_coef=0.1, value_loss_coef=1, policy_loss_coef=1, max_grad_norm=50, clone=False, use_tensorboard=True, decay_rate=0.0001, cuda='0', loss='l2', n_epochs=400, batch_size=4, task='train', hidden_dim=128, num_steps=20, rot_angle=4, action_num=5, num_point=2048, data_type='single_scan', data_dir='./dataset', result_dir='./output', pretrain_dir=None, note='debug', device=device(type='cuda'))
length of TRAIN_DATASET:18460
length of TEST_DATASET:2350
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0.0001
)
<torch.optim.lr_scheduler.StepLR object at 0x0000018135CD7FD0>

Epoch 1 (1/400):
Traceback (most recent call last):
  File "c:\Users\User\Desktop\UprightRL-main\code\main.py", line 738, in <module>
    main(args)
  File "c:\Users\User\Desktop\UprightRL-main\code\main.py", line 710, in main
    train(args, 'train', trainDataLoader, model, optimizer, epoch, summary_writer)
  File "c:\Users\User\Desktop\UprightRL-main\code\main.py", line 334, in train
    log_string(logger, mode+' error axis l2: %f' % np.mean(error_axis_l2_sum))
  File "c:\Users\User\Desktop\UprightRL-main\code\main.py", line 85, in log_string
    logger.info(str)
AttributeError: 'SummaryWriter' object has no attribute 'info'

**Comment by Juzhan** [comment]
你好，感谢你的反馈，这里是代码的一句bug，应该在 main.py 的[710行](https://github.com/RunningChen/UprightRL/blob/683e427242bd1282b0ad9a5c39b6d8f5ccf5a37e/code/main.py#LL711C14-L711C14)这里：
` train(args, 'train', trainDataLoader, model, optimizer, epoch, summary_writer)`
修改为
` train(args, 'train', trainDataLoader, model, optimizer, epoch, logger, summary_writer)`
补充一个参数logger，你遇到的报错是因为缺少这个变量导致一些文字打印失败，修改后应该是能正常训练的。

**Comment by firecoolman** [comment]
感謝版主大大，現在已經成功訓練起來了，太感謝版主的回覆了，想順便請教版主有嘗試過訓練自己的訓練集嗎?
我想要改輸入自己STL檔案，用版主的程式轉正

**Comment by Juzhan** [comment]
哈哈哈不客气，这是我们应该做的。我们提供的数据集shape_single_scan，其实就是我们自己用shapenet的模型收集的，在blender内用相机拍摄得到的点云，应该符合你说的“自己的训练集”吧，在那个数据集下算法也可以学会转正的策略。如果你使用自己训练集的时候遇到什么问题也欢迎咨询。

**Comment by firecoolman** [comment]
好的，感謝版主大大，我也來嘗試製作自己的資料集，非常感謝
