### ISSUE TITLE
想請教當初是如何製作資料集

### ISSUE THREAD

**Issue by firecoolman** [RunningChen/UprightRL#2]
之前再努力實作版主的程式碼，最近是開始製作自己的資料集了，想請問當時是如何製作的，想詢問blender這段是如何從shapenet製作檔案的，因為shapenet本身就是點雲，所以想請教當初版主是如何製作訓練集，這部分再麻煩版主了，非常感謝

**Comment by Juzhan** [comment]
我们使用的数据集是ShapeNetCore，这个是有带3D模型的，比如这个下载连接：http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1.zip。

印象中我们是使用这个blender代码生成点云的：https://github.com/itsumu/virtual_scan

你也可以使用https://github.com/DIYer22/bpycv 这个库，先获取深度图，再转成点云。

**Comment by firecoolman** [comment]
十分感謝版主的回答，我馬上來研究製作自己的資料集，順便想請問版主，這樣如何讓資料做出標註，例如我現在想要桌子轉正之後，桌面可以朝下，請問這樣我需要對資料集做甚麼動作嗎?

**Comment by Juzhan** [comment]
对数据集可能不用做什么处理，但算法实现上应该要进行调整，我们是要求统一朝正上方，所以计算奖励函数和评估准确率的时候都是和正方向计算角度误差。按你的需求，在计算的时候要改成和这个正方向所在的轴计算角度误差。

**Comment by firecoolman** [comment]
好的，感謝版主，我先試驗看看
